version: "3"

services:
  app:
    user: "1000"
    image: exekias/beats-demo-app
    volumes:
      - ./app:/src/app

  nginx:
    image: exekias/beats-demo-nginx
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=beats_demo_app
      - MYSQL_USER=beats
      - MYSQL_PASSWORD=foobar
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql/data

volumes:
  db-data:
