apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beats-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beats-demo
  template:
    metadata:
      labels:
        app: beats-demo
      annotations:
        co.elastic.logs.nginx/module: nginx
        co.elastic.logs.nginx/fileset.stdout: access
        co.elastic.logs.nginx/fileset.stderr: error
    spec:
      containers:
      - image: exekias/beats-demo-app
        imagePullPolicy: Always
        name: app
        resources:
          limits:
            cpu: 200m
        env:
        - name: APM_SERVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beats-demo
              key: MYSQL_PASSWORD
      - image: exekias/beats-demo-nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: 100m
        ports:
        - containerPort: 8080
      hostAliases:
      - ip: 127.0.0.1
        hostnames:
        - app
---
# Create tables on first run:
apiVersion: batch/v1
kind: Job
metadata:
  name: beats-demo-app-init
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: beats-demo
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: exekias/beats-demo-app
        command: ["django-admin",  "migrate"]
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beats-demo
              key: MYSQL_PASSWORD
