apiVersion: v1
kind: Service
metadata:
  name: beats-demo
spec:
  type: LoadBalancer
  loadBalancerIP: 35.187.174.238
  # Avoid NAT to get source IP:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: beats-demo
